package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Calculo;

/**
 *
 * @author Davi Alves de Lima
 * @since 23/03/2019
 * @version 1.0 Aragorn Version
 */
public class UIBhaskara extends javax.swing.JFrame {
    
    /**
     * Creates new form UIBhaskara
     */
    public UIBhaskara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgResults = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jlValueA = new javax.swing.JLabel();
        jtValueA = new javax.swing.JTextField();
        jlValueB = new javax.swing.JLabel();
        jtValueB = new javax.swing.JTextField();
        jlValueC = new javax.swing.JLabel();
        jtValueC = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jrResult = new javax.swing.JRadioButton();
        jrResolution = new javax.swing.JRadioButton();
        jrBoth = new javax.swing.JRadioButton();
        jbSubmit = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtResult = new javax.swing.JTextArea();
        jbClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Báskara"));

        jlValueA.setText("Valor de A=");

        jtValueA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtValueAKeyPressed(evt);
            }
        });

        jlValueB.setText("Valor de B=");

        jtValueB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtValueBKeyPressed(evt);
            }
        });

        jlValueC.setText("Valor de C=");

        jtValueC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtValueCKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jlValueA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtValueA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jlValueC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtValueC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jlValueB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtValueB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValueA)
                    .addComponent(jtValueA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValueB)
                    .addComponent(jtValueB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtValueC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlValueC))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jlValueA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtValueA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlValueB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtValueB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jlValueC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtValueC, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bgResults.add(jrResult);
        jrResult.setText("Resultado Apenas");
        jrResult.setActionCommand("result");
        jrResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrResultKeyPressed(evt);
            }
        });

        bgResults.add(jrResolution);
        jrResolution.setText("Resolução Apenas");
        jrResolution.setActionCommand("resolution");
        jrResolution.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrResolutionKeyPressed(evt);
            }
        });

        bgResults.add(jrBoth);
        jrBoth.setText("Ambos");
        jrBoth.setActionCommand("both");
        jrBoth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrBothKeyPressed(evt);
            }
        });

        jbSubmit.setText("Calcular");
        jbSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubmitActionPerformed(evt);
            }
        });
        jbSubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbSubmitKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrResolution)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jrBoth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSubmit))
                    .addComponent(jrResult))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrResolution)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrBoth)
                    .addComponent(jbSubmit))
                .addGap(19, 19, 19))
        );
        jLayeredPane3.setLayer(jrResult, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jrResolution, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jrBoth, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbSubmit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jtResult.setEditable(false);
        jtResult.setColumns(20);
        jtResult.setRows(5);
        jScrollPane1.setViewportView(jtResult);

        jbClean.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jbClean.setText("Limpar");
        jbClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCleanActionPerformed(evt);
            }
        });
        jbClean.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCleanKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jbClean)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbClean, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane4.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jbClean, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLayeredPane2)
                        .addGap(12, 12, 12)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jLayeredPane4)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return verify if the text fields are empty, if they are, returns a JOptionPaneMsg with a error message.
     */
    private void submit(){
        Calculo calc = new Calculo();
        
        if(!"".equals(jtValueA.getText()) || !"".equals(jtValueB.getText()) || !"".equals(jtValueC.getText())){
            calc.setValueA(Double.parseDouble(jtValueA.getText()));
            calc.setValueB(Double.parseDouble(jtValueB.getText()));
            calc.setValueC(Double.parseDouble(jtValueC.getText()));  
            switch (bgResults.getSelection().getActionCommand()) {
                case "both":
                    jtResult.setText(calc.results(bgResults.getSelection().getActionCommand()));
                    JOptionPane.showMessageDialog(rootPane, calc.results("result"));
                    break;
                case "result":
                    JOptionPane.showMessageDialog(rootPane, calc.results(bgResults.getSelection().getActionCommand()), "Resultado", JOptionPane.PLAIN_MESSAGE);
                    break;
                default:
                    jtResult.setText(calc.results(bgResults.getSelection().getActionCommand()));
                    break;  //closes the if
            }//closes the switch
        }else{
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos", "Erro", JOptionPane.PLAIN_MESSAGE);
        }
    }
    
    /**
     * clean all the text areas
     */
    private void clean(){
        jtValueA.setText("");
        jtValueB.setText("");
        jtValueC.setText("");
        jtResult.setText("");
        bgResults.clearSelection();
        jtValueA.grabFocus();
    }
    
    private void jtValueAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtValueAKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            jtValueB.grabFocus();
        }
    }//GEN-LAST:event_jtValueAKeyPressed

    private void jtValueBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtValueBKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            jtValueC.grabFocus();
        }
    }//GEN-LAST:event_jtValueBKeyPressed

    private void jtValueCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtValueCKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            jrResult.grabFocus();
        }
    }//GEN-LAST:event_jtValueCKeyPressed

    private void jrResultKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrResultKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            jrResolution.grabFocus();
        }
    }//GEN-LAST:event_jrResultKeyPressed

    private void jrResolutionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrResolutionKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            jrBoth.grabFocus();
        }
    }//GEN-LAST:event_jrResolutionKeyPressed

    private void jrBothKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrBothKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            jbSubmit.grabFocus();
        }
    }//GEN-LAST:event_jrBothKeyPressed

    private void jbSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubmitActionPerformed
        submit();
    }//GEN-LAST:event_jbSubmitActionPerformed

    private void jbSubmitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSubmitKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            submit();
        }
    }//GEN-LAST:event_jbSubmitKeyPressed

    private void jbCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCleanActionPerformed
        clean();
    }//GEN-LAST:event_jbCleanActionPerformed

    private void jbCleanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCleanKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            clean();
        }
    }//GEN-LAST:event_jbCleanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIBhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIBhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIBhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIBhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UIBhaskara().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgResults;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbClean;
    private javax.swing.JButton jbSubmit;
    private javax.swing.JLabel jlValueA;
    private javax.swing.JLabel jlValueB;
    private javax.swing.JLabel jlValueC;
    private javax.swing.JRadioButton jrBoth;
    private javax.swing.JRadioButton jrResolution;
    private javax.swing.JRadioButton jrResult;
    private javax.swing.JTextArea jtResult;
    private javax.swing.JTextField jtValueA;
    private javax.swing.JTextField jtValueB;
    private javax.swing.JTextField jtValueC;
    // End of variables declaration//GEN-END:variables
}
